// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeraGo.Infrastructure.Context;

#nullable disable

namespace SeraGo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907120000_AddAiJobClassification")]
    public partial class AddAiJobClassification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Placeholder — the real model snapshot lives in the latest *_ModelSnapshot.
            // This migration only adds two nullable columns, both of which already
            // exist in the current model via the Job entity update.
        }
    }
}
