// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeraGo.Infrastructure.Context;

#nullable disable

namespace SeraGo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260816090322_AddSavedJob")]
    partial class AddSavedJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aufy.Core.AufyRefreshToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("AufyRefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyLogoUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExperienceLevel")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectorName")
                        .HasColumnType("text");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PostedByUserId");

                    b.HasIndex("SectorId");

                    b.HasIndex("SourceName");

                    b.HasIndex("Status");

                    b.HasIndex("SourceName", "ExternalId")
                        .IsUnique();

                    b.HasIndex("IsActive", "Status", "PublishedAt")
                        .IsDescending(false, false, true);

                    b.HasIndex("SectorId", "Status", "IsActive");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.RecruiterProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyLogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanySize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("RecruiterProfiles");
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.SavedJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyLogoUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "JobId")
                        .IsUnique();

                    b.ToTable("SavedJobs");
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Sectors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9844),
                            IsActive = true,
                            Name = "Technology & IT",
                            Slug = "technology-it",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9847)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9865),
                            IsActive = true,
                            Name = "Accounting & Finance",
                            Slug = "accounting-finance",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9866)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9868),
                            IsActive = true,
                            Name = "Banking & Insurance",
                            Slug = "banking-insurance",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9868)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9870),
                            IsActive = true,
                            Name = "Sales & Marketing",
                            Slug = "sales-marketing",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9871)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9901),
                            IsActive = true,
                            Name = "Healthcare",
                            Slug = "healthcare",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9901)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9904),
                            IsActive = true,
                            Name = "Education & Training",
                            Slug = "education-training",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9904)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9906),
                            IsActive = true,
                            Name = "Engineering & Construction",
                            Slug = "engineering-construction",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9906)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9908),
                            IsActive = true,
                            Name = "Human Resources",
                            Slug = "human-resources",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9909)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9910),
                            IsActive = true,
                            Name = "Business & Administration",
                            Slug = "business-administration",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9910)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9911),
                            IsActive = true,
                            Name = "Manufacturing & Production",
                            Slug = "manufacturing-production",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9912)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9913),
                            IsActive = true,
                            Name = "Logistics & Transportation",
                            Slug = "logistics-transportation",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9913)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9915),
                            IsActive = true,
                            Name = "Procurement & Supply Chain",
                            Slug = "procurement-supply-chain",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9916)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000d"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9918),
                            IsActive = true,
                            Name = "Media & Communication",
                            Slug = "media-communication",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9918)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000e"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9919),
                            IsActive = true,
                            Name = "Design & Creative",
                            Slug = "design-creative",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9919)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000f"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9921),
                            IsActive = true,
                            Name = "Customer Service & Support",
                            Slug = "customer-service-support",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9921)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9922),
                            IsActive = true,
                            Name = "Hospitality & Tourism",
                            Slug = "hospitality-tourism",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9923)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9924),
                            IsActive = true,
                            Name = "Agriculture & Natural Science",
                            Slug = "agriculture-natural-science",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9924)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9927),
                            IsActive = true,
                            Name = "Legal",
                            Slug = "legal",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9927)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9928),
                            IsActive = true,
                            Name = "Social Science & Community",
                            Slug = "social-science-community",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9928)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9930),
                            IsActive = true,
                            Name = "Security & Protection",
                            Slug = "security-protection",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9930)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9931),
                            IsActive = true,
                            Name = "Skilled & General Labor",
                            Slug = "skilled-general-labor",
                            UpdatedAt = new DateTime(2026, 8, 16, 9, 3, 22, 115, DateTimeKind.Utc).AddTicks(9932)
                        });
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.SectorAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("SectorId");

                    b.ToTable("SectorAliases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000000"),
                            Alias = "information technology",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Alias = "technology",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Alias = "tech",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Alias = "it",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Alias = "ict",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            Alias = "it support",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            Alias = "computer science and information technology",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            Alias = "it, computer science and software engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            Alias = "software design & development",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000009"),
                            Alias = "data science & analytics",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000a"),
                            Alias = "software",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000b"),
                            Alias = "computer science",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000c"),
                            Alias = "accounting & finance",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000d"),
                            Alias = "accounting",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000e"),
                            Alias = "finance",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000f"),
                            Alias = "accounting and finance",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000010"),
                            Alias = "economics",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000011"),
                            Alias = "tax",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000012"),
                            Alias = "audit",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000013"),
                            Alias = "bookkeeping",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000014"),
                            Alias = "banking and insurance",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000015"),
                            Alias = "banking",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000016"),
                            Alias = "insurance",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000017"),
                            Alias = "insurance and investment",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000018"),
                            Alias = "sales & promotion",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000019"),
                            Alias = "sales",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001a"),
                            Alias = "marketing",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001b"),
                            Alias = "sales and marketing",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001c"),
                            Alias = "business sales and marketing",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001d"),
                            Alias = "marketing management",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001e"),
                            Alias = "digital marketing",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001f"),
                            Alias = "promotion",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000020"),
                            Alias = "healthcare",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000021"),
                            Alias = "health care",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000022"),
                            Alias = "health care management",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000023"),
                            Alias = "public health",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000024"),
                            Alias = "nursing",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000025"),
                            Alias = "pharmaceutical",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000026"),
                            Alias = "pharmacy",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000027"),
                            Alias = "medicine",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000028"),
                            Alias = "medical",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000029"),
                            Alias = "teaching & education",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002a"),
                            Alias = "education",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002b"),
                            Alias = "teaching",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002c"),
                            Alias = "tutoring, training & mentorship",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002d"),
                            Alias = "language and literature",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002e"),
                            Alias = "education management",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002f"),
                            Alias = "tutoring",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000030"),
                            Alias = "training",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000031"),
                            Alias = "engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000032"),
                            Alias = "construction & civil engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000033"),
                            Alias = "civil engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000034"),
                            Alias = "mechanical & electrical engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000035"),
                            Alias = "chemical & biomedical engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000036"),
                            Alias = "environmental, mining & energy engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000037"),
                            Alias = "manufacturing engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000038"),
                            Alias = "architectural engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000039"),
                            Alias = "automotive engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003a"),
                            Alias = "sanitary engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003b"),
                            Alias = "biomedical engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003c"),
                            Alias = "electrical engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003d"),
                            Alias = "architecture & urban planning",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003e"),
                            Alias = "construction skilled worker",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003f"),
                            Alias = "mechanical engineering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000040"),
                            Alias = "planning",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000041"),
                            Alias = "water and sanitation",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000042"),
                            Alias = "automotive",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000043"),
                            Alias = "human resource & talent management",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000044"),
                            Alias = "human resource and recruitment",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000045"),
                            Alias = "human resource administration",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000046"),
                            Alias = "human resources",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000047"),
                            Alias = "hr",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000048"),
                            Alias = "recruitment",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000049"),
                            Alias = "human resource",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000004a"),
                            Alias = "talent management",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000004b"),
                            Alias = "business",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000004c"),
                            Alias = "business administration",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000004d"),
                            Alias = "business administration & operations",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000004e"),
                            Alias = "business and administration",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000004f"),
                            Alias = "secretarial, admin and clerical",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000050"),
                            Alias = "secretarial & office management",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000051"),
                            Alias = "management",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000052"),
                            Alias = "development and project management",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000053"),
                            Alias = "advisory & consultancy",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000054"),
                            Alias = "brokerage & case closing",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000055"),
                            Alias = "business management",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000056"),
                            Alias = "administration",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000057"),
                            Alias = "office management",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000058"),
                            Alias = "secretarial",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000059"),
                            Alias = "manufacturing & production",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000005a"),
                            Alias = "manufacturing",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000005b"),
                            Alias = "manufacturing management",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000005c"),
                            Alias = "fmcg and manufacturing",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000005d"),
                            Alias = "woodwork & carpentry",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000005e"),
                            Alias = "production",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000005f"),
                            Alias = "transportation & delivery",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000060"),
                            Alias = "transportation & logistics",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000061"),
                            Alias = "transportation management",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000062"),
                            Alias = "transportation",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000063"),
                            Alias = "logistics & supply chain",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000064"),
                            Alias = "logistics, transport and supply chain",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000065"),
                            Alias = "logistics",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000066"),
                            Alias = "warehouse, supply chain and distribution",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000067"),
                            Alias = "purchasing & procurement",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000068"),
                            Alias = "supply chain & purchasing management",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000069"),
                            Alias = "procurement",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000006a"),
                            Alias = "supply chain",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000006b"),
                            Alias = "purchasing",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000006c"),
                            Alias = "media & entertainment",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000006d"),
                            Alias = "media and communication",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000006e"),
                            Alias = "multimedia content production",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000006f"),
                            Alias = "documentation & writing",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000070"),
                            Alias = "translation & transcription",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000071"),
                            Alias = "media",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000072"),
                            Alias = "journalism",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000073"),
                            Alias = "communication",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000074"),
                            Alias = "writing",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000075"),
                            Alias = "creative art & design",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000076"),
                            Alias = "fashion / clothing & textile design",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000077"),
                            Alias = "design",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000078"),
                            Alias = "graphic design",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000079"),
                            Alias = "creative",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000007a"),
                            Alias = "fashion design",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000007b"),
                            Alias = "creative arts",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000007c"),
                            Alias = "ui/ux design",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000007d"),
                            Alias = "fashion",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000007e"),
                            Alias = "customer service & care",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000007f"),
                            Alias = "retail & office support",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000080"),
                            Alias = "customer service",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000081"),
                            Alias = "support",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000082"),
                            Alias = "call center",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000083"),
                            Alias = "reception",
                            SectorId = new Guid("a0000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000084"),
                            Alias = "hospitality & tourism",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000085"),
                            Alias = "food & drink preparation / service",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000086"),
                            Alias = "hospitality",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000087"),
                            Alias = "tourism",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000088"),
                            Alias = "chef",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000089"),
                            Alias = "catering",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000008a"),
                            Alias = "hotel",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000008b"),
                            Alias = "agriculture",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000008c"),
                            Alias = "agricultural science",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000008d"),
                            Alias = "natural science",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000008e"),
                            Alias = "natural sciences",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000008f"),
                            Alias = "chemistry",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000090"),
                            Alias = "physics",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000091"),
                            Alias = "microbiology",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000092"),
                            Alias = "mathematics",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000093"),
                            Alias = "nutrition",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000094"),
                            Alias = "biology",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000095"),
                            Alias = "law & legal advocacy",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000096"),
                            Alias = "legal services",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000097"),
                            Alias = "legal",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000098"),
                            Alias = "law",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000099"),
                            Alias = "advocacy",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000009a"),
                            Alias = "social sciences and community service",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000009b"),
                            Alias = "social science",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000009c"),
                            Alias = "social work",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000009d"),
                            Alias = "community service",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000009e"),
                            Alias = "history",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000009f"),
                            Alias = "sociology",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-0000000000a0"),
                            Alias = "psychology",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-0000000000a1"),
                            Alias = "security",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-0000000000a2"),
                            Alias = "protection",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-0000000000a3"),
                            Alias = "guard",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-0000000000a4"),
                            Alias = "safety",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-0000000000a5"),
                            Alias = "low and medium skilled worker",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-0000000000a6"),
                            Alias = "service industry skilled worker",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-0000000000a7"),
                            Alias = "janitorial & office services",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-0000000000a8"),
                            Alias = "general labor",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-0000000000a9"),
                            Alias = "cleaner",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-0000000000aa"),
                            Alias = "maintenance",
                            SectorId = new Guid("a0000000-0000-0000-0000-000000000015")
                        });
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SyncState");
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.TalentProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Availability")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int[]>("DesiredJobTypes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<List<string>>("DesiredRoles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("ExperienceLevel")
                        .HasColumnType("integer");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PortfolioUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<Guid>>("PreferredSectorIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WorkMode")
                        .HasColumnType("integer");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("TalentProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SeraGo.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SeraGo.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeraGo.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SeraGo.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.Job", b =>
                {
                    b.HasOne("SeraGo.Core.Domain.Entities.ApplicationUser", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeraGo.Core.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PostedBy");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.RecruiterProfile", b =>
                {
                    b.HasOne("SeraGo.Core.Domain.Entities.ApplicationUser", "User")
                        .WithOne("RecruiterProfile")
                        .HasForeignKey("SeraGo.Core.Domain.Entities.RecruiterProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.SavedJob", b =>
                {
                    b.HasOne("SeraGo.Core.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SeraGo.Core.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.SectorAlias", b =>
                {
                    b.HasOne("SeraGo.Core.Domain.Entities.Sector", "Sector")
                        .WithMany("Aliases")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.TalentProfile", b =>
                {
                    b.HasOne("SeraGo.Core.Domain.Entities.ApplicationUser", "User")
                        .WithOne("TalentProfile")
                        .HasForeignKey("SeraGo.Core.Domain.Entities.TalentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("RecruiterProfile");

                    b.Navigation("TalentProfile");
                });

            modelBuilder.Entity("SeraGo.Core.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
